//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InazumaElevenSaveEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InazumaElevenSaveEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, 0,10],
        ///		[10, &quot;FW&quot;, 0,00, 0,25],
        ///		[9, &quot;MF&quot;, 0,50, 0,45],
        ///		[8, &quot;MF&quot;, -0,50, 0,45],
        ///		[7, &quot;MF&quot;, 0,80, 0,45],
        ///		[6, &quot;MF&quot;, -0,80, 0,45],
        ///		[5, &quot;MF&quot;, 0,20, 0,45],
        ///		[4, &quot;MF&quot;, -0,20, 0,45],
        ///		[3, &quot;DF&quot;, 0,25, 0,65],
        ///		[2, &quot;DF&quot;, -0,25, 0,65],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, -0,45],
        ///		[10, &quot;FW&quot;, 0,00, -0,13],
        ///		[9, &quot;MF&quot;, 0,50, 0,23],
        ///		[8, &quot;MF&quot;, -0,50, 0,23],
        ///		[7, &quot;MF&quot;, 0,80, 0,53],
        ///	 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Albatross {
            get {
                return ResourceManager.GetString("F-Albatross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,60, 0,15],
        ///		[10, &quot;FW&quot;, -0,60, 0,15],
        ///		[9, &quot;FW&quot;, 0,00, 0,20],
        ///		[8, &quot;MF&quot;, -0,80, 0,38],
        ///		[7, &quot;MF&quot;, -0,30, 0,38],
        ///		[6, &quot;MF&quot;, 0,80, 0,38],
        ///		[5, &quot;MF&quot;, 0,30, 0,38],
        ///		[4, &quot;DF&quot;, -0,40, 0,65],
        ///		[3, &quot;DF&quot;, 0,40, 0,65],
        ///		[2, &quot;DF&quot;, 0,00, 0,65],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,50, -0,38],
        ///		[10, &quot;FW&quot;, -0,50, -0,38],
        ///		[9, &quot;FW&quot;, 0,00, 0,20],
        ///		[8, &quot;MF&quot;, -0,80, 0,38],
        ///		[7, &quot;MF&quot;, -0,30, 0,38], [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Alpha {
            get {
                return ResourceManager.GetString("F-Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, 0,13],
        ///		[10, &quot;MF&quot;, 0,60, 0,30],
        ///		[9, &quot;MF&quot;, -0,60, 0,30],
        ///		[8, &quot;MF&quot;, 0,00, 0,30],
        ///		[7, &quot;MF&quot;, 0,30, 0,45],
        ///		[6, &quot;MF&quot;, -0,30, 0,45],
        ///		[5, &quot;DF&quot;, 0,70, 0,55],
        ///		[4, &quot;DF&quot;, -0,70, 0,55],
        ///		[3, &quot;DF&quot;, 0,30, 0,65],
        ///		[2, &quot;DF&quot;, -0,30, 0,65],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, -0,58],
        ///		[10, &quot;MF&quot;, 0,50, 0,20],
        ///		[9, &quot;MF&quot;, -0,50, 0,20],
        ///		[8, &quot;MF&quot;, 0,00, -0,23],
        ///		[7, &quot;MF&quot;, 0,20, 0,30],
        ///	 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Ancient_Power {
            get {
                return ResourceManager.GetString("F-Ancient Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,20, 0,11],
        ///		[10, &quot;FW&quot;, -0,20, 0,11],
        ///		[9, &quot;MF&quot;, 0,39, 0,29],
        ///		[8, &quot;MF&quot;, 0,00, 0,38],
        ///		[7, &quot;MF&quot;, -0,39, 0,29],
        ///		[6, &quot;MF&quot;, 0,70, 0,41],
        ///		[5, &quot;MF&quot;, -0,70, 0,41],
        ///		[4, &quot;DF&quot;, 0,50, 0,65],
        ///		[3, &quot;DF&quot;, 0,00, 0,65],
        ///		[2, &quot;DF&quot;, -0,50, 0,65],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,45, -0,38],
        ///		[10, &quot;FW&quot;, -0,45, -0,38],
        ///		[9, &quot;MF&quot;, 0,25, 0,25],
        ///		[8, &quot;MF&quot;, 0,00, -0,03],
        ///		[7, &quot;MF&quot;, -0,25, 0,25], [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Antlers {
            get {
                return ResourceManager.GetString("F-Antlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;MF&quot;, 0,00, 0,35],
        ///		[10, &quot;FW&quot;, 0,00, 0,13],
        ///		[9, &quot;MF&quot;, 0,40, 0,25],
        ///		[8, &quot;MF&quot;, 0,70, 0,40],
        ///		[7, &quot;MF&quot;, -0,70, 0,40],
        ///		[6, &quot;MF&quot;, -0,40, 0,25],
        ///		[5, &quot;DF&quot;, 0,40, 0,70],
        ///		[4, &quot;DF&quot;, -0,40, 0,70],
        ///		[3, &quot;DF&quot;, 0,20, 0,53],
        ///		[2, &quot;DF&quot;, -0,20, 0,53],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;MF&quot;, 0,00, 0,45],
        ///		[10, &quot;FW&quot;, 0,00, -0,13],
        ///		[9, &quot;MF&quot;, 0,35, 0,25],
        ///		[8, &quot;MF&quot;, 0,70, 0,40],
        ///		[7, &quot;MF&quot;, -0,70, 0,40],
        ///		 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Avalanche {
            get {
                return ResourceManager.GetString("F-Avalanche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,20, 0,15],
        ///		[10, &quot;FW&quot;, -0,20, 0,15],
        ///		[9, &quot;MF&quot;, 0,70, 0,30],
        ///		[8, &quot;MF&quot;, -0,70, 0,30],
        ///		[7, &quot;MF&quot;, 0,20, 0,40],
        ///		[6, &quot;MF&quot;, -0,20, 0,40],
        ///		[5, &quot;DF&quot;, 0,70, 0,55],
        ///		[4, &quot;DF&quot;, -0,70, 0,55],
        ///		[3, &quot;DF&quot;, 0,20, 0,65],
        ///		[2, &quot;DF&quot;, -0,20, 0,65],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,35, -0,38],
        ///		[10, &quot;FW&quot;, -0,40, -0,38],
        ///		[9, &quot;MF&quot;, 0,60, 0,05],
        ///		[8, &quot;MF&quot;, -0,60, 0,05],
        ///		[7, &quot;MF&quot;, 0,15, 0,25], [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Basic {
            get {
                return ResourceManager.GetString("F-Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,50, 0,10],
        ///		[10, &quot;FW&quot;, 0,00, 0,15],
        ///		[9, &quot;FW&quot;, -0,50, 0,10],
        ///		[8, &quot;MF&quot;, -0,55, 0,43],
        ///		[7, &quot;MF&quot;, 0,00, 0,50],
        ///		[6, &quot;MF&quot;, 0,55, 0,43],
        ///		[5, &quot;MF&quot;, 0,00, 0,33],
        ///		[4, &quot;DF&quot;, -0,60, 0,68],
        ///		[3, &quot;DF&quot;, 0,60, 0,68],
        ///		[2, &quot;DF&quot;, 0,00, 0,68],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,50, 0,03],
        ///		[10, &quot;FW&quot;, 0,00, -0,23],
        ///		[9, &quot;FW&quot;, -0,50, 0,03],
        ///		[8, &quot;MF&quot;, -0,55, 0,40],
        ///		[7, &quot;MF&quot;, 0,00, 0,45],
        ///		 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Beta {
            get {
                return ResourceManager.GetString("F-Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;MF&quot;, 0,00, 0,35],
        ///		[10, &quot;FW&quot;, 0,00, 0,18],
        ///		[9, &quot;MF&quot;, 0,40, 0,35],
        ///		[8, &quot;MF&quot;, -0,40, 0,35],
        ///		[7, &quot;DF&quot;, 0,00, 0,53],
        ///		[6, &quot;DF&quot;, 0,80, 0,70],
        ///		[5, &quot;DF&quot;, 0,40, 0,70],
        ///		[4, &quot;DF&quot;, 0,00, 0,70],
        ///		[3, &quot;DF&quot;, -0,40, 0,70],
        ///		[2, &quot;DF&quot;, -0,80, 0,70],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;MF&quot;, 0,00, 0,13],
        ///		[10, &quot;FW&quot;, 0,00, -0,18],
        ///		[9, &quot;MF&quot;, 0,50, 0,20],
        ///		[8, &quot;MF&quot;, -0,50, 0,20],
        ///		[7, &quot;DF&quot;, 0,00, 0,38],
        ///		[ [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Big_Bang {
            get {
                return ResourceManager.GetString("F-Big Bang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,75, 0,10],
        ///		[10, &quot;FW&quot;, 0,00, 0,20],
        ///		[9, &quot;FW&quot;, -0,75, 0,10],
        ///		[8, &quot;MF&quot;, 0,50, 0,28],
        ///		[7, &quot;MF&quot;, -0,50, 0,28],
        ///		[6, &quot;DF&quot;, 0,30, 0,48],
        ///		[5, &quot;DF&quot;, -0,30, 0,48],
        ///		[4, &quot;DF&quot;, 0,55, 0,65],
        ///		[3, &quot;DF&quot;, 0,00, 0,65],
        ///		[2, &quot;DF&quot;, -0,55, 0,65],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,75, 0,05],
        ///		[10, &quot;FW&quot;, 0,00, -0,23],
        ///		[9, &quot;FW&quot;, -0,75, 0,05],
        ///		[8, &quot;MF&quot;, 0,50, 0,28],
        ///		[7, &quot;MF&quot;, -0,50, 0,28],
        ///	 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Black_Hole {
            get {
                return ResourceManager.GetString("F-Black Hole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,40, 0,13],
        ///		[10, &quot;FW&quot;, -0,40, 0,13],
        ///		[9, &quot;MF&quot;, 0,70, 0,30],
        ///		[8, &quot;MF&quot;, -0,70, 0,30],
        ///		[7, &quot;MF&quot;, 0,20, 0,30],
        ///		[6, &quot;MF&quot;, -0,20, 0,30],
        ///		[5, &quot;DF&quot;, 0,40, 0,58],
        ///		[4, &quot;DF&quot;, -0,40, 0,58],
        ///		[3, &quot;DF&quot;, 0,00, 0,48],
        ///		[2, &quot;DF&quot;, 0,00, 0,68],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,25, -0,53],
        ///		[10, &quot;FW&quot;, -0,25, -0,53],
        ///		[9, &quot;MF&quot;, 0,60, -0,08],
        ///		[8, &quot;MF&quot;, -0,60, -0,08],
        ///		[7, &quot;MF&quot;, 0,20, 0,10] [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Blue_Leaves {
            get {
                return ResourceManager.GetString("F-Blue Leaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,63, 0,15],
        ///		[10, &quot;FW&quot;, -0,63, 0,15],
        ///		[9, &quot;FW&quot;, 0,00, 0,15],
        ///		[8, &quot;MF&quot;, 0,50, 0,35],
        ///		[7, &quot;MF&quot;, -0,50, 0,35],
        ///		[6, &quot;MF&quot;, 0,00, 0,35],
        ///		[5, &quot;DF&quot;, 0,80, 0,55],
        ///		[4, &quot;DF&quot;, -0,80, 0,55],
        ///		[3, &quot;DF&quot;, 0,30, 0,65],
        ///		[2, &quot;DF&quot;, -0,30, 0,65],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,45, -0,10],
        ///		[10, &quot;FW&quot;, -0,45, -0,10],
        ///		[9, &quot;FW&quot;, 0,00, -0,33],
        ///		[8, &quot;MF&quot;, 0,50, 0,30],
        ///		[7, &quot;MF&quot;, -0,50, 0,30], [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Broadsword {
            get {
                return ResourceManager.GetString("F-Broadsword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,50, 0,18],
        ///		[10, &quot;FW&quot;, 0,00, 0,18],
        ///		[9, &quot;FW&quot;, -0,50, 0,18],
        ///		[8, &quot;MF&quot;, 0,60, 0,38],
        ///		[7, &quot;MF&quot;, 0,00, 0,45],
        ///		[6, &quot;MF&quot;, -0,60, 0,38],
        ///		[5, &quot;DF&quot;, 0,70, 0,58],
        ///		[4, &quot;DF&quot;, 0,25, 0,65],
        ///		[3, &quot;DF&quot;, -0,25, 0,65],
        ///		[2, &quot;DF&quot;, -0,70, 0,58],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,60, -0,15],
        ///		[10, &quot;FW&quot;, 0,00, 0,03],
        ///		[9, &quot;FW&quot;, -0,60, -0,15],
        ///		[8, &quot;MF&quot;, 0,60, 0,28],
        ///		[7, &quot;MF&quot;, 0,00, 0,43],
        ///	 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Burning_Soul {
            get {
                return ResourceManager.GetString("F-Burning Soul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,55, 0,23],
        ///		[10, &quot;FW&quot;, 0,00, 0,18],
        ///		[9, &quot;FW&quot;, -0,55, 0,23],
        ///		[8, &quot;MF&quot;, 0,70, 0,45],
        ///		[7, &quot;MF&quot;, 0,25, 0,38],
        ///		[6, &quot;MF&quot;, -0,25, 0,38],
        ///		[5, &quot;MF&quot;, -0,70, 0,45],
        ///		[4, &quot;DF&quot;, 0,40, 0,63],
        ///		[3, &quot;DF&quot;, 0,00, 0,58],
        ///		[2, &quot;DF&quot;, -0,40, 0,63],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,50, 0,08],
        ///		[10, &quot;FW&quot;, 0,00, -0,28],
        ///		[9, &quot;FW&quot;, -0,50, 0,08],
        ///		[8, &quot;MF&quot;, 0,70, 0,45],
        ///		[7, &quot;MF&quot;, 0,30, 0,28],
        ///		 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Coup_d_Etat {
            get {
                return ResourceManager.GetString("F-Coup d\'Etat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, 0,13],
        ///		[10, &quot;MF&quot;, 0,70, 0,33],
        ///		[9, &quot;MF&quot;, 0,25, 0,33],
        ///		[8, &quot;MF&quot;, -0,25, 0,33],
        ///		[7, &quot;MF&quot;, -0,70, 0,33],
        ///		[6, &quot;DF&quot;, 0,50, 0,50],
        ///		[5, &quot;DF&quot;, 0,20, 0,70],
        ///		[4, &quot;DF&quot;, 0,00, 0,50],
        ///		[3, &quot;DF&quot;, -0,20, 0,70],
        ///		[2, &quot;DF&quot;, -0,50, 0,50],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, -0,08],
        ///		[10, &quot;MF&quot;, 0,70, 0,30],
        ///		[9, &quot;MF&quot;, 0,25, 0,30],
        ///		[8, &quot;MF&quot;, -0,25, 0,30],
        ///		[7, &quot;MF&quot;, -0,70, 0,30],
        ///	 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Defence_Formation {
            get {
                return ResourceManager.GetString("F-Defence Formation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,70, 0,13],
        ///		[10, &quot;FW&quot;, -0,70, 0,13],
        ///		[9, &quot;FW&quot;, 0,25, 0,13],
        ///		[8, &quot;FW&quot;, -0,25, 0,13],
        ///		[7, &quot;MF&quot;, 0,00, 0,30],
        ///		[6, &quot;MF&quot;, 0,45, 0,40],
        ///		[5, &quot;MF&quot;, -0,45, 0,40],
        ///		[4, &quot;MF&quot;, 0,00, 0,50],
        ///		[3, &quot;DF&quot;, 0,25, 0,68],
        ///		[2, &quot;DF&quot;, -0,25, 0,68],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,45, -0,50],
        ///		[10, &quot;FW&quot;, -0,45, -0,50],
        ///		[9, &quot;FW&quot;, 0,20, -0,15],
        ///		[8, &quot;FW&quot;, -0,20, -0,15],
        ///		[7, &quot;MF&quot;, 0,00, 0,08] [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Divinity {
            get {
                return ResourceManager.GetString("F-Divinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,35, 0,08],
        ///		[10, &quot;FW&quot;, -0,35, 0,08],
        ///		[9, &quot;MF&quot;, 0,70, 0,28],
        ///		[8, &quot;MF&quot;, 0,35, 0,48],
        ///		[7, &quot;MF&quot;, 0,00, 0,30],
        ///		[6, &quot;MF&quot;, -0,35, 0,48],
        ///		[5, &quot;MF&quot;, -0,70, 0,28],
        ///		[4, &quot;DF&quot;, 0,80, 0,63],
        ///		[3, &quot;DF&quot;, 0,00, 0,65],
        ///		[2, &quot;DF&quot;, -0,80, 0,63],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,35, -0,25],
        ///		[10, &quot;FW&quot;, -0,35, -0,25],
        ///		[9, &quot;MF&quot;, 0,70, 0,10],
        ///		[8, &quot;MF&quot;, 0,35, 0,40],
        ///		[7, &quot;MF&quot;, 0,00, 0,23],
        ///	 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Flower_of_Chaos {
            get {
                return ResourceManager.GetString("F-Flower of Chaos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,35, 0,10],
        ///		[10, &quot;FW&quot;, 0,00, 0,18],
        ///		[9, &quot;FW&quot;, -0,35, 0,10],
        ///		[8, &quot;MF&quot;, 0,80, 0,23],
        ///		[7, &quot;MF&quot;, 0,42, 0,35],
        ///		[6, &quot;MF&quot;, 0,00, 0,40],
        ///		[5, &quot;MF&quot;, -0,42, 0,35],
        ///		[4, &quot;MF&quot;, -0,80, 0,23],
        ///		[3, &quot;DF&quot;, 0,20, 0,60],
        ///		[2, &quot;DF&quot;, -0,20, 0,60],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,35, -0,23],
        ///		[10, &quot;FW&quot;, 0,00, 0,18],
        ///		[9, &quot;FW&quot;, -0,35, -0,23],
        ///		[8, &quot;MF&quot;, 0,75, 0,33],
        ///		[7, &quot;MF&quot;, 0,50, 0,43],
        ///	 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Full_Moon {
            get {
                return ResourceManager.GetString("F-Full Moon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,30, 0,10],
        ///		[10, &quot;FW&quot;, -0,30, 0,10],
        ///		[9, &quot;MF&quot;, 0,00, 0,30],
        ///		[8, &quot;MF&quot;, 0,75, 0,35],
        ///		[7, &quot;MF&quot;, 0,35, 0,40],
        ///		[6, &quot;MF&quot;, -0,35, 0,40],
        ///		[5, &quot;MF&quot;, -0,75, 0,35],
        ///		[4, &quot;DF&quot;, 0,55, 0,63],
        ///		[3, &quot;DF&quot;, 0,00, 0,63],
        ///		[2, &quot;DF&quot;, -0,55, 0,63],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,30, 0,10],
        ///		[10, &quot;FW&quot;, -0,30, 0,10],
        ///		[9, &quot;MF&quot;, 0,00, 0,40],
        ///		[8, &quot;MF&quot;, 0,75, 0,48],
        ///		[7, &quot;MF&quot;, 0,25, 0,53],
        ///		[ [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Gahl {
            get {
                return ResourceManager.GetString("F-Gahl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,30, 0,15],
        ///		[10, &quot;FW&quot;, -0,30, 0,15],
        ///		[9, &quot;MF&quot;, 0,60, 0,28],
        ///		[8, &quot;MF&quot;, 0,00, 0,33],
        ///		[7, &quot;MF&quot;, -0,60, 0,28],
        ///		[6, &quot;DF&quot;, 0,00, 0,50],
        ///		[5, &quot;DF&quot;, 0,60, 0,65],
        ///		[4, &quot;DF&quot;, 0,30, 0,58],
        ///		[3, &quot;DF&quot;, -0,30, 0,58],
        ///		[2, &quot;DF&quot;, -0,60, 0,65],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,35, -0,20],
        ///		[10, &quot;FW&quot;, -0,35, -0,20],
        ///		[9, &quot;MF&quot;, 0,55, 0,18],
        ///		[8, &quot;MF&quot;, 0,00, 0,23],
        ///		[7, &quot;MF&quot;, -0,55, 0,18],
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Galaxy {
            get {
                return ResourceManager.GetString("F-Galaxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,70, 0,10],
        ///		[10, &quot;FW&quot;, 0,00, 0,18],
        ///		[9, &quot;FW&quot;, -0,70, 0,10],
        ///		[8, &quot;MF&quot;, 0,40, 0,25],
        ///		[7, &quot;MF&quot;, -0,70, 0,38],
        ///		[6, &quot;MF&quot;, 0,70, 0,38],
        ///		[5, &quot;MF&quot;, -0,40, 0,25],
        ///		[4, &quot;DF&quot;, 0,00, 0,45],
        ///		[3, &quot;DF&quot;, 0,50, 0,63],
        ///		[2, &quot;DF&quot;, -0,50, 0,63],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,70, 0,10],
        ///		[10, &quot;FW&quot;, 0,00, -0,08],
        ///		[9, &quot;FW&quot;, -0,70, 0,10],
        ///		[8, &quot;MF&quot;, 0,35, 0,38],
        ///		[7, &quot;MF&quot;, -0,65, 0,50],
        ///	 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Gamma {
            get {
                return ResourceManager.GetString("F-Gamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,60, 0,10],
        ///		[10, &quot;FW&quot;, -0,60, 0,10],
        ///		[9, &quot;MF&quot;, 0,20, 0,23],
        ///		[8, &quot;MF&quot;, -0,20, 0,23],
        ///		[7, &quot;MF&quot;, 0,55, 0,38],
        ///		[6, &quot;MF&quot;, 0,00, 0,45],
        ///		[5, &quot;MF&quot;, -0,55, 0,38],
        ///		[4, &quot;DF&quot;, 0,55, 0,63],
        ///		[3, &quot;DF&quot;, 0,00, 0,63],
        ///		[2, &quot;DF&quot;, -0,55, 0,63],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,60, 0,08],
        ///		[10, &quot;FW&quot;, -0,60, 0,08],
        ///		[9, &quot;MF&quot;, 0,30, 0,35],
        ///		[8, &quot;MF&quot;, -0,30, 0,35],
        ///		[7, &quot;MF&quot;, 0,65, 0,45],
        ///		 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Gihl {
            get {
                return ResourceManager.GetString("F-Gihl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,60, 0,18],
        ///		[10, &quot;FW&quot;, 0,00, 0,18],
        ///		[9, &quot;FW&quot;, -0,60, 0,18],
        ///		[8, &quot;MF&quot;, 0,45, 0,35],
        ///		[7, &quot;MF&quot;, 0,00, 0,35],
        ///		[6, &quot;MF&quot;, -0,45, 0,35],
        ///		[5, &quot;MF&quot;, 0,30, 0,53],
        ///		[4, &quot;MF&quot;, -0,30, 0,53],
        ///		[3, &quot;DF&quot;, 0,20, 0,70],
        ///		[2, &quot;DF&quot;, -0,20, 0,70],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,75, -0,23],
        ///		[10, &quot;FW&quot;, 0,00, -0,03],
        ///		[9, &quot;FW&quot;, -0,75, -0,23],
        ///		[8, &quot;MF&quot;, 0,65, 0,15],
        ///		[7, &quot;MF&quot;, 0,00, 0,28],
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Grace_Fin {
            get {
                return ResourceManager.GetString("F-Grace Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, 0,35],
        ///		[10, &quot;FW&quot;, 0,00, 0,18],
        ///		[9, &quot;MF&quot;, 0,40, 0,30],
        ///		[8, &quot;MF&quot;, -0,40, 0,30],
        ///		[7, &quot;MF&quot;, 0,80, 0,40],
        ///		[6, &quot;MF&quot;, 0,40, 0,50],
        ///		[5, &quot;MF&quot;, -0,40, 0,50],
        ///		[4, &quot;MF&quot;, -0,80, 0,40],
        ///		[3, &quot;DF&quot;, 0,00, 0,55],
        ///		[2, &quot;DF&quot;, 0,00, 0,73],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, 0,03],
        ///		[10, &quot;FW&quot;, 0,00, -0,25],
        ///		[9, &quot;MF&quot;, 0,35, 0,20],
        ///		[8, &quot;MF&quot;, -0,35, 0,20],
        ///		[7, &quot;MF&quot;, 0,80, 0,33],
        ///		[ [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Hunters {
            get {
                return ResourceManager.GetString("F-Hunters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,70, 0,18],
        ///		[10, &quot;FW&quot;, -0,70, 0,18],
        ///		[9, &quot;FW&quot;, -0,25, 0,18],
        ///		[8, &quot;FW&quot;, 0,25, 0,18],
        ///		[7, &quot;MF&quot;, 0,00, 0,40],
        ///		[6, &quot;DF&quot;, 0,80, 0,63],
        ///		[5, &quot;DF&quot;, 0,40, 0,63],
        ///		[4, &quot;DF&quot;, 0,00, 0,63],
        ///		[3, &quot;DF&quot;, -0,40, 0,63],
        ///		[2, &quot;DF&quot;, -0,80, 0,63],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,70, 0,18],
        ///		[10, &quot;FW&quot;, -0,70, 0,18],
        ///		[9, &quot;FW&quot;, -0,25, 0,18],
        ///		[8, &quot;FW&quot;, 0,25, 0,18],
        ///		[7, &quot;MF&quot;, 0,00, 0,40],
        ///		 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Iron_Shell {
            get {
                return ResourceManager.GetString("F-Iron Shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, 0,15],
        ///		[10, &quot;FW&quot;, 0,00, 0,35],
        ///		[9, &quot;MF&quot;, 0,40, 0,35],
        ///		[8, &quot;MF&quot;, -0,40, 0,35],
        ///		[7, &quot;DF&quot;, 0,83, 0,63],
        ///		[6, &quot;DF&quot;, -0,83, 0,63],
        ///		[5, &quot;DF&quot;, 0,48, 0,63],
        ///		[4, &quot;DF&quot;, -0,48, 0,63],
        ///		[3, &quot;DF&quot;, 0,15, 0,63],
        ///		[2, &quot;DF&quot;, -0,15, 0,63],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, 0,28],
        ///		[10, &quot;FW&quot;, 0,00, 0,58],
        ///		[9, &quot;MF&quot;, 0,50, 0,08],
        ///		[8, &quot;MF&quot;, -0,50, 0,08],
        ///		[7, &quot;DF&quot;, 0,85, 0,45],
        ///		[ [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Legacy {
            get {
                return ResourceManager.GetString("F-Legacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,30, 0,13],
        ///		[10, &quot;FW&quot;, -0,30, 0,13],
        ///		[9, &quot;MF&quot;, 0,00, 0,48],
        ///		[8, &quot;MF&quot;, 0,00, 0,28],
        ///		[7, &quot;MF&quot;, 0,55, 0,33],
        ///		[6, &quot;MF&quot;, -0,55, 0,33],
        ///		[5, &quot;DF&quot;, 0,70, 0,60],
        ///		[4, &quot;DF&quot;, 0,20, 0,65],
        ///		[3, &quot;DF&quot;, -0,20, 0,65],
        ///		[2, &quot;DF&quot;, -0,70, 0,60],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,35, -0,20],
        ///		[10, &quot;FW&quot;, -0,35, -0,20],
        ///		[9, &quot;MF&quot;, 0,00, 0,48],
        ///		[8, &quot;MF&quot;, 0,00, -0,08],
        ///		[7, &quot;MF&quot;, 0,45, 0,28],
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Lightning {
            get {
                return ResourceManager.GetString("F-Lightning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,40, 0,15],
        ///		[10, &quot;FW&quot;, -0,40, 0,15],
        ///		[9, &quot;MF&quot;, 0,70, 0,30],
        ///		[8, &quot;MF&quot;, -0,70, 0,30],
        ///		[7, &quot;MF&quot;, 0,00, 0,30],
        ///		[6, &quot;MF&quot;, 0,30, 0,45],
        ///		[5, &quot;MF&quot;, -0,30, 0,45],
        ///		[4, &quot;DF&quot;, 0,40, 0,65],
        ///		[3, &quot;DF&quot;, -0,40, 0,65],
        ///		[2, &quot;DF&quot;, 0,00, 0,60],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,40, -0,48],
        ///		[10, &quot;FW&quot;, -0,40, -0,48],
        ///		[9, &quot;MF&quot;, 0,70, 0,13],
        ///		[8, &quot;MF&quot;, -0,70, 0,13],
        ///		[7, &quot;MF&quot;, 0,00, 0,13],
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Lobster_Claw {
            get {
                return ResourceManager.GetString("F-Lobster Claw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,65, 0,23],
        ///		[10, &quot;FW&quot;, 0,20, 0,18],
        ///		[9, &quot;FW&quot;, -0,20, 0,18],
        ///		[8, &quot;FW&quot;, -0,65, 0,23],
        ///		[7, &quot;MF&quot;, 0,30, 0,35],
        ///		[6, &quot;MF&quot;, -0,30, 0,35],
        ///		[5, &quot;MF&quot;, 0,30, 0,53],
        ///		[4, &quot;MF&quot;, -0,30, 0,53],
        ///		[3, &quot;DF&quot;, 0,30, 0,70],
        ///		[2, &quot;DF&quot;, -0,30, 0,70],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,65, -0,08],
        ///		[10, &quot;FW&quot;, 0,25, -0,33],
        ///		[9, &quot;FW&quot;, -0,25, -0,33],
        ///		[8, &quot;FW&quot;, -0,65, -0,08],
        ///		[7, &quot;MF&quot;, 0,30, 0,15 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Lost_Wing {
            get {
                return ResourceManager.GetString("F-Lost Wing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,30, 0,15],
        ///		[10, &quot;FW&quot;, -0,30, 0,15],
        ///		[9, &quot;FW&quot;, 0,00, 0,15],
        ///		[8, &quot;MF&quot;, 0,40, 0,40],
        ///		[7, &quot;MF&quot;, -0,40, 0,40],
        ///		[6, &quot;MF&quot;, 0,00, 0,33],
        ///		[5, &quot;DF&quot;, 0,70, 0,55],
        ///		[4, &quot;DF&quot;, -0,70, 0,55],
        ///		[3, &quot;DF&quot;, 0,20, 0,65],
        ///		[2, &quot;DF&quot;, -0,20, 0,65],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,20, -0,32],
        ///		[10, &quot;FW&quot;, -0,20, -0,32],
        ///		[9, &quot;FW&quot;, 0,00, -0,53],
        ///		[8, &quot;MF&quot;, 0,30, 0,40],
        ///		[7, &quot;MF&quot;, -0,30, 0,40], [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Moonlight {
            get {
                return ResourceManager.GetString("F-Moonlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, 0,15],
        ///		[10, &quot;MF&quot;, 0,60, 0,25],
        ///		[9, &quot;MF&quot;, -0,60, 0,25],
        ///		[8, &quot;MF&quot;, 0,30, 0,33],
        ///		[7, &quot;MF&quot;, -0,30, 0,33],
        ///		[6, &quot;MF&quot;, 0,20, 0,50],
        ///		[5, &quot;MF&quot;, -0,20, 0,50],
        ///		[4, &quot;DF&quot;, 0,50, 0,68],
        ///		[3, &quot;DF&quot;, -0,50, 0,68],
        ///		[2, &quot;DF&quot;, 0,00, 0,68],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, -0,53],
        ///		[10, &quot;MF&quot;, 0,40, -0,28],
        ///		[9, &quot;MF&quot;, -0,40, -0,28],
        ///		[8, &quot;MF&quot;, 0,50, 0,08],
        ///		[7, &quot;MF&quot;, -0,50, 0,08], [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Neo_Cloud {
            get {
                return ResourceManager.GetString("F-Neo Cloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,40, 0,15],
        ///		[10, &quot;FW&quot;, -0,40, 0,15],
        ///		[9, &quot;MF&quot;, 0,00, 0,32],
        ///		[8, &quot;MF&quot;, 0,60, 0,35],
        ///		[7, &quot;MF&quot;, -0,60, 0,35],
        ///		[6, &quot;MF&quot;, 0,00, 0,53],
        ///		[5, &quot;DF&quot;, 0,80, 0,55],
        ///		[4, &quot;DF&quot;, -0,80, 0,55],
        ///		[3, &quot;DF&quot;, 0,30, 0,65],
        ///		[2, &quot;DF&quot;, -0,30, 0,65],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,50, -0,25],
        ///		[10, &quot;FW&quot;, -0,50, -0,25],
        ///		[9, &quot;MF&quot;, 0,00, -0,03],
        ///		[8, &quot;MF&quot;, 0,65, 0,20],
        ///		[7, &quot;MF&quot;, -0,65, 0,20], [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Neo_Death_Zone {
            get {
                return ResourceManager.GetString("F-Neo Death Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,25, 0,13],
        ///		[10, &quot;FW&quot;, -0,25, 0,13],
        ///		[9, &quot;MF&quot;, 0,00, 0,40],
        ///		[8, &quot;MF&quot;, 0,45, 0,33],
        ///		[7, &quot;MF&quot;, -0,45, 0,33],
        ///		[6, &quot;MF&quot;, 0,75, 0,48],
        ///		[5, &quot;MF&quot;, -0,75, 0,48],
        ///		[4, &quot;DF&quot;, 0,55, 0,65],
        ///		[3, &quot;DF&quot;, 0,00, 0,70],
        ///		[2, &quot;DF&quot;, -0,55, 0,65],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,30, 0,10],
        ///		[10, &quot;FW&quot;, -0,30, 0,10],
        ///		[9, &quot;MF&quot;, 0,00, 0,40],
        ///		[8, &quot;MF&quot;, 0,50, 0,30],
        ///		[7, &quot;MF&quot;, -0,50, 0,30],
        ///		 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_New_Moon {
            get {
                return ResourceManager.GetString("F-New Moon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,50, 0,10],
        ///		[10, &quot;FW&quot;, 0,00, 0,18],
        ///		[9, &quot;FW&quot;, -0,50, 0,10],
        ///		[8, &quot;MF&quot;, 0,70, 0,30],
        ///		[7, &quot;MF&quot;, 0,00, 0,38],
        ///		[6, &quot;MF&quot;, -0,70, 0,30],
        ///		[5, &quot;DF&quot;, 0,80, 0,58],
        ///		[4, &quot;DF&quot;, 0,30, 0,58],
        ///		[3, &quot;DF&quot;, -0,30, 0,58],
        ///		[2, &quot;DF&quot;, -0,80, 0,58],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,60, -0,30],
        ///		[10, &quot;FW&quot;, 0,00, -0,15],
        ///		[9, &quot;FW&quot;, -0,60, -0,30],
        ///		[8, &quot;MF&quot;, 0,70, 0,05],
        ///		[7, &quot;MF&quot;, 0,00, 0,25],
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Oasis_Route {
            get {
                return ResourceManager.GetString("F-Oasis Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,55, 0,10],
        ///		[10, &quot;FW&quot;, -0,55, 0,10],
        ///		[9, &quot;MF&quot;, 0,25, 0,25],
        ///		[8, &quot;MF&quot;, 0,45, 0,45],
        ///		[7, &quot;MF&quot;, -0,45, 0,45],
        ///		[6, &quot;MF&quot;, -0,25, 0,25],
        ///		[5, &quot;DF&quot;, 0,75, 0,58],
        ///		[4, &quot;DF&quot;, 0,30, 0,65],
        ///		[3, &quot;DF&quot;, -0,30, 0,65],
        ///		[2, &quot;DF&quot;, -0,75, 0,58],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,55, -0,13],
        ///		[10, &quot;FW&quot;, -0,55, -0,13],
        ///		[9, &quot;MF&quot;, 0,25, 0,18],
        ///		[8, &quot;MF&quot;, 0,45, 0,40],
        ///		[7, &quot;MF&quot;, -0,45, 0,40], [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Ocean_Dive {
            get {
                return ResourceManager.GetString("F-Ocean Dive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,70, 0,20],
        ///		[10, &quot;FW&quot;, -0,70, 0,20],
        ///		[9, &quot;FW&quot;, 0,00, 0,15],
        ///		[8, &quot;MF&quot;, 0,30, 0,30],
        ///		[7, &quot;MF&quot;, -0,30, 0,30],
        ///		[6, &quot;MF&quot;, 0,00, 0,45],
        ///		[5, &quot;DF&quot;, 0,80, 0,55],
        ///		[4, &quot;DF&quot;, -0,80, 0,55],
        ///		[3, &quot;DF&quot;, 0,30, 0,65],
        ///		[2, &quot;DF&quot;, -0,30, 0,65],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,80, -0,18],
        ///		[10, &quot;FW&quot;, -0,80, -0,15],
        ///		[9, &quot;FW&quot;, 0,00, -0,48],
        ///		[8, &quot;MF&quot;, 0,50, 0,30],
        ///		[7, &quot;MF&quot;, -0,50, 0,30], [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Omnipresence {
            get {
                return ResourceManager.GetString("F-Omnipresence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,60, 0,15],
        ///		[10, &quot;FW&quot;, -0,60, 0,15],
        ///		[9, &quot;FW&quot;, 0,20, 0,15],
        ///		[8, &quot;FW&quot;, -0,20, 0,15],
        ///		[7, &quot;MF&quot;, 0,60, 0,40],
        ///		[6, &quot;MF&quot;, -0,60, 0,40],
        ///		[5, &quot;MF&quot;, 0,20, 0,40],
        ///		[4, &quot;MF&quot;, -0,20, 0,40],
        ///		[3, &quot;DF&quot;, 0,20, 0,65],
        ///		[2, &quot;DF&quot;, -0,20, 0,65],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,60, -0,03],
        ///		[10, &quot;FW&quot;, -0,60, -0,03],
        ///		[9, &quot;FW&quot;, 0,20, -0,03],
        ///		[8, &quot;FW&quot;, -0,20, -0,03],
        ///		[7, &quot;MF&quot;, 0,60, 0,25 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_One_Thousand {
            get {
                return ResourceManager.GetString("F-One Thousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, 0,35],
        ///		[10, &quot;FW&quot;, 0,00, 0,18],
        ///		[9, &quot;FW&quot;, 0,40, 0,35],
        ///		[8, &quot;FW&quot;, -0,40, 0,35],
        ///		[7, &quot;MF&quot;, 0,75, 0,45],
        ///		[6, &quot;MF&quot;, 0,00, 0,53],
        ///		[5, &quot;MF&quot;, -0,75, 0,45],
        ///		[4, &quot;DF&quot;, 0,40, 0,70],
        ///		[3, &quot;DF&quot;, 0,00, 0,70],
        ///		[2, &quot;DF&quot;, -0,40, 0,70],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, 0,18],
        ///		[10, &quot;FW&quot;, 0,00, -0,35],
        ///		[9, &quot;FW&quot;, 0,65, 0,03],
        ///		[8, &quot;FW&quot;, -0,65, 0,03],
        ///		[7, &quot;MF&quot;, 0,70, 0,33],
        ///		[ [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Orbius {
            get {
                return ResourceManager.GetString("F-Orbius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, 0,18],
        ///		[10, &quot;MF&quot;, 0,30, 0,23],
        ///		[9, &quot;MF&quot;, -0,30, 0,23],
        ///		[8, &quot;MF&quot;, 0,80, 0,33],
        ///		[7, &quot;MF&quot;, 0,30, 0,43],
        ///		[6, &quot;MF&quot;, -0,30, 0,43],
        ///		[5, &quot;MF&quot;, -0,80, 0,33],
        ///		[4, &quot;DF&quot;, 0,40, 0,63],
        ///		[3, &quot;DF&quot;, 0,00, 0,65],
        ///		[2, &quot;DF&quot;, -0,40, 0,63],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, -0,25],
        ///		[10, &quot;MF&quot;, 0,30, 0,08],
        ///		[9, &quot;MF&quot;, -0,30, 0,08],
        ///		[8, &quot;MF&quot;, 0,80, 0,33],
        ///		[7, &quot;MF&quot;, 0,30, 0,43],
        ///		 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Pakichi_Smell {
            get {
                return ResourceManager.GetString("F-Pakichi Smell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,25, 0,13],
        ///		[10, &quot;FW&quot;, -0,25, 0,13],
        ///		[9, &quot;MF&quot;, 0,00, 0,38],
        ///		[8, &quot;MF&quot;, 0,65, 0,28],
        ///		[7, &quot;MF&quot;, -0,65, 0,28],
        ///		[6, &quot;MF&quot;, 0,65, 0,48],
        ///		[5, &quot;MF&quot;, -0,65, 0,48],
        ///		[4, &quot;DF&quot;, 0,35, 0,60],
        ///		[3, &quot;DF&quot;, 0,00, 0,65],
        ///		[2, &quot;DF&quot;, -0,35, 0,60],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,35, -0,08],
        ///		[10, &quot;FW&quot;, -0,35, -0,08],
        ///		[9, &quot;MF&quot;, 0,00, 0,43],
        ///		[8, &quot;MF&quot;, 0,55, 0,33],
        ///		[7, &quot;MF&quot;, -0,55, 0,33],
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Perfection {
            get {
                return ResourceManager.GetString("F-Perfection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,25, 0,12],
        ///		[10, &quot;FW&quot;, -0,25, 0,12],
        ///		[9, &quot;MF&quot;, 0,00, 0,30],
        ///		[8, &quot;MF&quot;, 0,55, 0,35],
        ///		[7, &quot;MF&quot;, -0,55, 0,35],
        ///		[6, &quot;MF&quot;, 0,00, 0,49],
        ///		[5, &quot;DF&quot;, 0,75, 0,55],
        ///		[4, &quot;DF&quot;, -0,75, 0,55],
        ///		[3, &quot;DF&quot;, 0,25, 0,68],
        ///		[2, &quot;DF&quot;, -0,25, 0,68],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,25, -0,53],
        ///		[10, &quot;FW&quot;, -0,25, -0,53],
        ///		[9, &quot;MF&quot;, 0,00, -0,30],
        ///		[8, &quot;MF&quot;, 0,55, 0,05],
        ///		[7, &quot;MF&quot;, -0,55, 0,05], [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Phantom {
            get {
                return ResourceManager.GetString("F-Phantom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,55, 0,15],
        ///		[10, &quot;FW&quot;, 0,00, 0,13],
        ///		[9, &quot;FW&quot;, -0,55, 0,15],
        ///		[8, &quot;MF&quot;, 0,00, 0,33],
        ///		[7, &quot;MF&quot;, 0,55, 0,38],
        ///		[6, &quot;MF&quot;, -0,55, 0,38],
        ///		[5, &quot;DF&quot;, 0,80, 0,58],
        ///		[4, &quot;DF&quot;, 0,25, 0,63],
        ///		[3, &quot;DF&quot;, -0,25, 0,63],
        ///		[2, &quot;DF&quot;, -0,80, 0,58],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,55, 0,15],
        ///		[10, &quot;FW&quot;, 0,00, -0,13],
        ///		[9, &quot;FW&quot;, -0,55, 0,15],
        ///		[8, &quot;MF&quot;, 0,00, 0,25],
        ///		[7, &quot;MF&quot;, 0,45, 0,45],
        ///		 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Predator {
            get {
                return ResourceManager.GetString("F-Predator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,35, 0,10],
        ///		[10, &quot;FW&quot;, -0,35, 0,10],
        ///		[9, &quot;MF&quot;, 0,65, 0,23],
        ///		[8, &quot;MF&quot;, -0,65, 0,23],
        ///		[7, &quot;MF&quot;, 0,45, 0,40],
        ///		[6, &quot;MF&quot;, 0,00, 0,45],
        ///		[5, &quot;MF&quot;, -0,45, 0,40],
        ///		[4, &quot;DF&quot;, 0,70, 0,58],
        ///		[3, &quot;DF&quot;, 0,00, 0,65],
        ///		[2, &quot;DF&quot;, -0,70, 0,58],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,35, 0,05],
        ///		[10, &quot;FW&quot;, -0,35, 0,05],
        ///		[9, &quot;MF&quot;, 0,60, 0,35],
        ///		[8, &quot;MF&quot;, -0,60, 0,35],
        ///		[7, &quot;MF&quot;, 0,30, 0,48],
        ///		 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Ragnah {
            get {
                return ResourceManager.GetString("F-Ragnah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,40, 0,13],
        ///		[10, &quot;FW&quot;, -0,40, 0,13],
        ///		[9, &quot;FW&quot;, 0,00, 0,25],
        ///		[8, &quot;MF&quot;, 0,63, 0,32],
        ///		[7, &quot;MF&quot;, -0,63, 0,32],
        ///		[6, &quot;MF&quot;, 0,00, 0,45],
        ///		[5, &quot;DF&quot;, 0,80, 0,55],
        ///		[4, &quot;DF&quot;, -0,80, 0,55],
        ///		[3, &quot;DF&quot;, 0,30, 0,65],
        ///		[2, &quot;DF&quot;, -0,30, 0,65],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,50, -0,30],
        ///		[10, &quot;FW&quot;, -0,50, -0,30],
        ///		[9, &quot;FW&quot;, 0,00, -0,18],
        ///		[8, &quot;MF&quot;, 0,50, 0,30],
        ///		[7, &quot;MF&quot;, -0,50, 0,30], [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Raimon {
            get {
                return ResourceManager.GetString("F-Raimon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,60, 0,15],
        ///		[10, &quot;FW&quot;, -0,60, 0,15],
        ///		[9, &quot;MF&quot;, 0,00, 0,18],
        ///		[8, &quot;MF&quot;, 0,00, 0,35],
        ///		[7, &quot;MF&quot;, 0,50, 0,40],
        ///		[6, &quot;MF&quot;, -0,50, 0,40],
        ///		[5, &quot;DF&quot;, 0,80, 0,70],
        ///		[4, &quot;DF&quot;, -0,80, 0,70],
        ///		[3, &quot;DF&quot;, 0,30, 0,65],
        ///		[2, &quot;DF&quot;, -0,30, 0,65],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,60, -0,30],
        ///		[10, &quot;FW&quot;, -0,60, -0,30],
        ///		[9, &quot;MF&quot;, 0,00, -0,58],
        ///		[8, &quot;MF&quot;, 0,00, -0,05],
        ///		[7, &quot;MF&quot;, 0,30, 0,35], [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Resistance {
            get {
                return ResourceManager.GetString("F-Resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,30, 0,10],
        ///		[10, &quot;FW&quot;, -0,30, 0,10],
        ///		[9, &quot;MF&quot;, 0,75, 0,25],
        ///		[8, &quot;MF&quot;, 0,30, 0,35],
        ///		[7, &quot;MF&quot;, -0,30, 0,35],
        ///		[6, &quot;MF&quot;, -0,75, 0,25],
        ///		[5, &quot;DF&quot;, 0,75, 0,60],
        ///		[4, &quot;DF&quot;, 0,30, 0,60],
        ///		[3, &quot;DF&quot;, -0,30, 0,60],
        ///		[2, &quot;DF&quot;, -0,75, 0,60],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,30, -0,15],
        ///		[10, &quot;FW&quot;, -0,30, -0,15],
        ///		[9, &quot;MF&quot;, 0,75, 0,18],
        ///		[8, &quot;MF&quot;, 0,30, 0,35],
        ///		[7, &quot;MF&quot;, -0,30, 0,35], [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Sandstorm {
            get {
                return ResourceManager.GetString("F-Sandstorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,30, 0,15],
        ///		[10, &quot;FW&quot;, -0,30, 0,15],
        ///		[9, &quot;MF&quot;, 0,70, 0,30],
        ///		[8, &quot;MF&quot;, -0,70, 0,30],
        ///		[7, &quot;MF&quot;, 0,00, 0,33],
        ///		[6, &quot;MF&quot;, 0,25, 0,50],
        ///		[5, &quot;MF&quot;, -0,25, 0,50],
        ///		[4, &quot;DF&quot;, 0,40, 0,68],
        ///		[3, &quot;DF&quot;, -0,40, 0,68],
        ///		[2, &quot;DF&quot;, 0,00, 0,68],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,20, -0,50],
        ///		[10, &quot;FW&quot;, -0,20, -0,50],
        ///		[9, &quot;MF&quot;, 0,55, -0,08],
        ///		[8, &quot;MF&quot;, -0,55, -0,08],
        ///		[7, &quot;MF&quot;, 0,00, 0,28] [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Shining_Light {
            get {
                return ResourceManager.GetString("F-Shining Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,60, 0,15],
        ///		[10, &quot;FW&quot;, -0,60, 0,15],
        ///		[9, &quot;FW&quot;, 0,00, 0,15],
        ///		[8, &quot;MF&quot;, 0,80, 0,35],
        ///		[7, &quot;MF&quot;, -0,80, 0,35],
        ///		[6, &quot;MF&quot;, 0,30, 0,35],
        ///		[5, &quot;MF&quot;, -0,30, 0,35],
        ///		[4, &quot;DF&quot;, 0,40, 0,65],
        ///		[3, &quot;DF&quot;, -0,40, 0,65],
        ///		[2, &quot;DF&quot;, 0,00, 0,65],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,35, -0,30],
        ///		[10, &quot;FW&quot;, -0,35, -0,30],
        ///		[9, &quot;FW&quot;, 0,00, 0,05],
        ///		[8, &quot;MF&quot;, 0,80, 0,55],
        ///		[7, &quot;MF&quot;, -0,80, 0,55],
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Stratosphere {
            get {
                return ResourceManager.GetString("F-Stratosphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, 0,18],
        ///		[10, &quot;MF&quot;, 0,80, 0,30],
        ///		[9, &quot;MF&quot;, 0,35, 0,25],
        ///		[8, &quot;MF&quot;, -0,35, 0,25],
        ///		[7, &quot;MF&quot;, -0,80, 0,30],
        ///		[6, &quot;DF&quot;, 0,60, 0,63],
        ///		[5, &quot;DF&quot;, 0,30, 0,55],
        ///		[4, &quot;DF&quot;, 0,00, 0,63],
        ///		[3, &quot;DF&quot;, -0,30, 0,55],
        ///		[2, &quot;DF&quot;, -0,60, 0,63],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, -0,20],
        ///		[10, &quot;MF&quot;, 0,80, 0,30],
        ///		[9, &quot;MF&quot;, 0,25, 0,18],
        ///		[8, &quot;MF&quot;, -0,25, 0,18],
        ///		[7, &quot;MF&quot;, -0,80, 0,30],
        ///	 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Supernova {
            get {
                return ResourceManager.GetString("F-Supernova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, 0,13],
        ///		[10, &quot;MF&quot;, 0,75, 0,30],
        ///		[9, &quot;MF&quot;, 0,00, 0,30],
        ///		[8, &quot;MF&quot;, -0,75, 0,30],
        ///		[7, &quot;MF&quot;, 0,75, 0,48],
        ///		[6, &quot;MF&quot;, 0,00, 0,48],
        ///		[5, &quot;MF&quot;, -0,75, 0,48],
        ///		[4, &quot;DF&quot;, 0,75, 0,65],
        ///		[3, &quot;DF&quot;, 0,00, 0,65],
        ///		[2, &quot;DF&quot;, -0,75, 0,65],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, 0,05],
        ///		[10, &quot;MF&quot;, 0,45, 0,40],
        ///		[9, &quot;MF&quot;, 0,00, 0,40],
        ///		[8, &quot;MF&quot;, -0,45, 0,40],
        ///		[7, &quot;MF&quot;, 0,75, 0,53],
        ///		[6 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Terracotta {
            get {
                return ResourceManager.GetString("F-Terracotta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,55, 0,15],
        ///		[10, &quot;FW&quot;, -0,55, 0,15],
        ///		[9, &quot;MF&quot;, 0,00, 0,25],
        ///		[8, &quot;MF&quot;, 0,30, 0,35],
        ///		[7, &quot;MF&quot;, -0,30, 0,35],
        ///		[6, &quot;MF&quot;, 0,00, 0,45],
        ///		[5, &quot;DF&quot;, 0,60, 0,65],
        ///		[4, &quot;DF&quot;, -0,60, 0,65],
        ///		[3, &quot;DF&quot;, 0,20, 0,65],
        ///		[2, &quot;DF&quot;, -0,20, 0,65],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,55, -0,53],
        ///		[10, &quot;FW&quot;, -0,55, -0,53],
        ///		[9, &quot;MF&quot;, 0,00, -0,28],
        ///		[8, &quot;MF&quot;, 0,35, 0,05],
        ///		[7, &quot;MF&quot;, -0,35, 0,05], [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Tiger_Strike {
            get {
                return ResourceManager.GetString("F-Tiger Strike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, 0,10],
        ///		[10, &quot;MF&quot;, 0,40, 0,28],
        ///		[9, &quot;MF&quot;, -0,40, 0,28],
        ///		[8, &quot;MF&quot;, 0,00, 0,28],
        ///		[7, &quot;MF&quot;, 0,40, 0,45],
        ///		[6, &quot;MF&quot;, -0,40, 0,45],
        ///		[5, &quot;DF&quot;, 0,70, 0,65],
        ///		[4, &quot;DF&quot;, -0,70, 0,65],
        ///		[3, &quot;DF&quot;, 0,20, 0,65],
        ///		[2, &quot;DF&quot;, -0,20, 0,65],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, -0,53],
        ///		[10, &quot;MF&quot;, 0,50, 0,25],
        ///		[9, &quot;MF&quot;, -0,50, 0,25],
        ///		[8, &quot;MF&quot;, 0,00, -0,23],
        ///		[7, &quot;MF&quot;, 0,25, 0,48],
        ///	 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Youthful_Spirit {
            get {
                return ResourceManager.GetString("F-Youthful Spirit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, 0,12],
        ///		[10, &quot;MF&quot;, 0,80, 0,23],
        ///		[9, &quot;MF&quot;, 0,00, 0,30],
        ///		[8, &quot;MF&quot;, -0,80, 0,23],
        ///		[7, &quot;MF&quot;, 0,70, 0,43],
        ///		[6, &quot;MF&quot;, 0,00, 0,48],
        ///		[5, &quot;MF&quot;, -0,70, 0,43],
        ///		[4, &quot;DF&quot;, 0,45, 0,58],
        ///		[3, &quot;DF&quot;, 0,00, 0,65],
        ///		[2, &quot;DF&quot;, -0,45, 0,58],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,00, -0,05],
        ///		[10, &quot;MF&quot;, 0,80, 0,35],
        ///		[9, &quot;MF&quot;, 0,00, 0,38],
        ///		[8, &quot;MF&quot;, -0,80, 0,35],
        ///		[7, &quot;MF&quot;, 0,65, 0,50],
        ///		[ [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Zan {
            get {
                return ResourceManager.GetString("F-Zan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,45, 0,20],
        ///		[10, &quot;FW&quot;, 0,00, 0,13],
        ///		[9, &quot;FW&quot;, -0,45, 0,20],
        ///		[8, &quot;MF&quot;, 0,75, 0,30],
        ///		[7, &quot;MF&quot;, 0,30, 0,38],
        ///		[6, &quot;MF&quot;, -0,30, 0,38],
        ///		[5, &quot;MF&quot;, -0,75, 0,30],
        ///		[4, &quot;DF&quot;, 0,55, 0,60],
        ///		[3, &quot;DF&quot;, 0,00, 0,53],
        ///		[2, &quot;DF&quot;, -0,55, 0,60],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,55, -0,13],
        ///		[10, &quot;FW&quot;, 0,00, -0,30],
        ///		[9, &quot;FW&quot;, -0,55, -0,13],
        ///		[8, &quot;MF&quot;, 0,65, 0,28],
        ///		[7, &quot;MF&quot;, 0,40, 0,38],
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Zanark {
            get {
                return ResourceManager.GetString("F-Zanark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à form_start &lt;- {
        ///	name = &quot;form_start&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,25, 0,15],
        ///		[10, &quot;FW&quot;, -0,25, 0,15],
        ///		[9, &quot;MF&quot;, 0,70, 0,30],
        ///		[8, &quot;MF&quot;, -0,70, 0,30],
        ///		[7, &quot;MF&quot;, 0,25, 0,43],
        ///		[6, &quot;MF&quot;, -0,25, 0,43],
        ///		[5, &quot;DF&quot;, 0,70, 0,60],
        ///		[4, &quot;DF&quot;, -0,70, 0,60],
        ///		[3, &quot;DF&quot;, 0,25, 0,68],
        ///		[2, &quot;DF&quot;, -0,25, 0,68],
        ///		[1, &quot;GK&quot;, 0,00, 0,90],
        ///	],
        ///};
        ///
        ///form_def &lt;- {
        ///	name = &quot;form_def&quot;,
        ///	data = [
        ///		[11, &quot;FW&quot;, 0,25, 0,15],
        ///		[10, &quot;FW&quot;, -0,25, 0,15],
        ///		[9, &quot;MF&quot;, 0,70, 0,30],
        ///		[8, &quot;MF&quot;, -0,70, 0,30],
        ///		[7, &quot;MF&quot;, 0,25, 0,43],
        ///	 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string F_Zero {
            get {
                return ResourceManager.GetString("F-Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FormationTemplate {
            get {
                object obj = ResourceManager.GetObject("FormationTemplate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MovedPlayerRectangleBox {
            get {
                object obj = ResourceManager.GetObject("MovedPlayerRectangleBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerRectangleBox {
            get {
                object obj = ResourceManager.GetObject("PlayerRectangleBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
